worker_processes auto;
error_log /dev/stderr warn;
pid /var/run/nginx/nginx.pid;
events { worker_connections 4096; }
http {
  include /etc/nginx/mime.types;
  default_type application/octet-stream;
  access_log /dev/stdout;
  sendfile on;
  keepalive_timeout 65s;
  client_max_body_size 500m;
  include /etc/nginx/conf.d/*.conf;
}
