apiVersion: v1
kind: Secret
metadata:
  name: crest-db-secret
type: Opaque
stringData:
  CREST_DB_USERNAME: "CHANGE_ME_OB_USER@ob_oracle#obcluster"
  CREST_DB_PASSWORD: "CHANGE_ME_OB_PASSWORD"
  CREST_AES_KEY: "CHANGE_ME_AES_KEY_32_CHARS_00000"
  CREST_AES_IV: "CHANGE_ME_IV_16_"
  CREST_INITIAL_PASSWORD: "CHANGE_ME_INITIAL_ADMIN_PASSWORD"
  CREST_TOKEN_SECRET: "CHANGE_ME_LONG_RANDOM_TOKEN_SECRET"
