apiVersion: v1
kind: Service
metadata:
  name: crest-service
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: crest-service
    app.kubernetes.io/component: backend
  ports:
    - name: http
      port: 8100
      targetPort: http
