apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: crest
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - change-me-crest.example.invalid
      secretName: crest-tls
  rules:
    - host: change-me-crest.example.invalid
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: crest
                port:
                  number: 8100
