apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: crest-service
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: crest-service
      app.kubernetes.io/component: backend
