apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: crest-web
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: crest
      app.kubernetes.io/component: frontend
  policyTypes:
    - Ingress
  ingress:
    - ports:
        - protocol: TCP
          port: 8080
