apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: crest-service
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: crest-service
      app.kubernetes.io/component: backend
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: crest
              app.kubernetes.io/component: frontend
      ports:
        - protocol: TCP
          port: 8100
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: monitoring
          podSelector:
            matchLabels:
              app.kubernetes.io/name: prometheus
      ports:
        - protocol: TCP
          port: 8100
